# social_sources.py — Vietnamese Threads content sources
# Categories: News, Tech/Business, Entertainment, Lifestyle, Food, Travel, Beauty/Fashion, Sports

# ── Threads ────────────────────────────────────────────────────────────────────

THREADS_ACCOUNTS = [
    "sontungmtp",
    "chipupu",
    "ngoctrinh89",
    "kinglnd",
    "hoaminzy_rose",
    "toctien1305",
    "nguyenducphuc_",
    "soobin.hoangson",
    "singerdongnhi",
    "hienho2620",
    "hoangyenchibi812",
    "erikthanh_",
    "bichphuongofficial",
    "suboi",
    "justatee",
    "den.vau",
    "gil_le",
    "si.thanh",
    "min.st319",
    "junpham",

    # ───────── Fashion / Beauty Influencers ─────────
    "chaubui_",
    "quynhanhshyn_",
    "thaonhile",
    "hellytong",
    "kelbinlei",
    "phuongkhanh_official",
    "phuongly",
    "lamgia_khang",
    "nhung.gumiho",
    "sunht",
    "tranghy",
    "ngocthuyy",
    "beautyvietnam",
    "skincarevietnam",
    "depvietnam",
    "ellevietnam",

    # ───────── Lifestyle Creators ─────────
    "giangoi",
    "khanhvyccf",
    "thepresentwriter",
    "changmakeup",
    "phamhuynhnhatvi",
    "chanlaca",
    "lehautrung",
    "vietcetera",
    "maybevietnam",
    "tonybuoi",
    "beatvn",
    "saigonlife",
    "hanoicapital",

    # ───────── Food Creators ─────────
    "heominhon",
    "reviewanngon",
    "saigonfoodie",
    "hanoifoodie",
    "diadiemanuong",
    "foodyvn",
    "streetfoodvietnam",
    "anchoivietnam",
    "vietnamesestreetfood",
    "ansapsaigon",

    # ───────── Travel / Explore Vietnam ─────────
    "checkinvietnam",
    "vietnamtravel",
    "vietnamtourismboard",
    "explorevietnam",
    "danangfantasticity",
    "phuquocisland",
    "halongbayvietnam",
    "hoianancienttown",
    "vietnamtravels",

    # ───────── News / Media ─────────
    "vnexpress.net",
    "zingnews",
    "tuoitreonline",
    "thanhnien",
    "dantri.com.vn",
    "vietnamnet.vn",
    "vtv24news",
    "kenh14vn",
    "yan.vn",
    "cafebiz.vn",
    "cafef.vn",
    "genk.vn",

    # ───────── Tech / Startup ─────────
    "vietnamstartup",
    "topdev.vn",
    "techinasiavn",
    "fptsoftware",
    "viettelgroup",
    "vnpt.official",
    "momo.vn",
    "tiki.vn",
    "shopee_vn",

    # ───────── Gaming / Esports ─────────
    "lienquanmobile",
    "pubgmobile.vn",
    "valorantvn",
    "vnggames",
    "esportsvietnam",
    "gamingvietnam",
    "onlive.vn",

    # ───────── Additional VN Creators (long-tail accounts) ─────────
    "thachtrang",
    "quangvinh",
    "tranthanh",
    "hariwon",
    "lanngocnguyen",
    "phuonganhdao",
    "truonggiang",
    "lamvyda",
    "ngocanhwhite",
    "thutrangnguyen",
    "huonggiangggg",
    "vickivirus",
    "moontellthat",
    "uyenninh",
    "jennythaole",
    "linhngocdam.fan",
    "baotran",
    "hoangthuy",
    "minhhang",
    "thanhhang",
    "truongthanhlong",
    "anhduc",
    "nguyenminhtrang",
    "nhungbabie",
    "trinhpham",
    "phuongly",
    "tungmaru",
    "minhnhua",
    "thao.tam",
    "buitrang",
    "honganh",
    "huongly",
    "nhatle",
    "phuongthao",
    "linhmiu",
    "sam.sammie",
    "dieunhi",
    "thuyngan",
    "trangmoon",
    "anhquynh",
    "ngocdiep",
    "phuongthuy",
    "huongtram",
    "hoangyen",
    "ngocchau",
    "kimduyen",
    "thuytien",
    "doha",
    "lehang",
    "mypham",
    "ngocthao",
    "thuhoai",
    "quynhnga",
    "thanhthanhhien",
    "trinhthao",
    "ngoclinh",
    "nguyenanh",
    "anhthu",
    "trinhtrang",
    "minhchau",
    "ngocanh",
    "thuyduong",
    "huonggiang",
    "phuongmai",
    "thuyanh",
    "myanh",
    "anhthuofficial",
    "trangphap",
    "minhhangofficial",
    "truongquynhanh",
    "thanhhien",
    "kimchi",
    "miso",
    "buitrang",
    "nguyenhuyen",
    "trinhphuong",
    "lananh",
    "phuonganh",
    "thuylinh",
    "trangnguyen",
    "ngoclinhbeauty",
    "linhbeauty",
    "phuongbeauty",
    "saigonreview",
    "hanoireview",
    "danangreview",
    "vietnamreview",
    "foodreviewvietnam",
    "travelreviewvietnam"
]

THREADS_HASHTAGS = [
    "tintuc",
    "tintucvietnam",
    "thoisu",
    "xahoi",
    "kinhte",
    "doisong",
    "congdong",
    "vietnamnews",
    "vietnamtoday",
    "thoisu24h",
    "tinnhanh",
    "tinnong",
    "tintuc24h",

    # ───────── Technology / Startup ─────────
    "congnghe",
    "vietnamtech",
    "startup",
    "startupvietnam",
    "laptrinh",
    "codinglife",
    "devlife",
    "ai",
    "aiart",
    "machinelearning",
    "blockchain",
    "crypto",
    "chuyendoiso",
    "digitaltransformation",

    # ───────── Entertainment / Showbiz ─────────
    "giaitri",
    "showbiz",
    "showbizviet",
    "nhacviet",
    "rapviet",
    "phimviet",
    "phimhay",
    "reviewphim",
    "celeb",
    "celebvietnam",
    "saostar",
    "kenh14",
    "vietnamesemusic",
    "vpop",

    # ───────── Lifestyle ─────────
    "cuocsong",
    "cuocsongviet",
    "genzvietnam",
    "genzlife",
    "review",
    "reviewvietnam",
    "reviewdoisong",
    "sanphamtot",
    "meovat",
    "meovatcuocsong",
    "tamsu",
    "tamsusuckhoe",
    "songtichcuc",
    "motivationvietnam",
    "inspiration",

    # ───────── Relationship / Thoughts (popular on Threads) ─────────
    "tinhyeu",
    "tinhyeudep",
    "tinhyeuoi",
    "tamtrang",
    "tamtrangbuon",
    "tamtrangdem",
    "quotesvietnam",
    "vietquotes",
    "deepthoughts",
    "suynghi",
    "storytime",

    # ───────── Food / Drink ─────────
    "amthuc",
    "amthucviet",
    "monngon",
    "monngonmoingay",
    "reviewanngon",
    "foodreview",
    "foodvietnam",
    "vietnamesefood",
    "streetfood",
    "streetfoodvietnam",
    "anvat",
    "anvatsaigon",
    "anvathanoi",
    "quancafe",
    "cafevietnam",
    "trasua",
    "milktea",
    "foodblogger",
    "foodlover",

    # ───────── Travel ─────────
    "dulich",
    "dulichvietnam",
    "khamphavietnam",
    "travelvietnam",
    "checkinvietnam",
    "reviewdulich",
    "travellife",
    "wanderlust",
    "travelgram",
    "travelblogger",
    "saigon",
    "saigonlife",
    "saigonfood",
    "hanoi",
    "hanoilife",
    "danang",
    "phuquoc",
    "halongbay",
    "hoian",

    # ───────── Beauty / Fashion ─────────
    "thoitrang",
    "thoitrangviet",
    "fashion",
    "fashionvietnam",
    "streetstyle",
    "ootd",
    "outfitoftheday",
    "beauty",
    "beautyvietnam",
    "skincare",
    "skincareroutine",
    "makeup",
    "makeuptutorial",
    "makeupvietnam",
    "cosmetics",
    "mypham",
    "reviewmypham",

    # ───────── Sports ─────────
    "bongda",
    "bongdavietnam",
    "football",
    "sports",
    "sportlife",
    "gym",
    "fitness",
    "fitnessvietnam",
    "workout",
    "gymlife",
    "bodybuilding",

    # ───────── Gaming / Esports ─────────
    "gaming",
    "game",
    "gamevietnam",
    "gamer",
    "gamerlife",
    "esports",
    "esportsvietnam",
    "lienquan",
    "lienquanmobile",
    "pubgmobile",
    "pubgmobilevn",
    "valorant",
    "valorantvn",

    # ───────── Creator / Viral ─────────
    "viral",
    "trending",
    "trendvietnam",
    "hottrend",
    "fyp",
    "fypvietnam",
    "explore",
    "explorepage",
    "reelsvietnam",
    "contentcreator",
    "creatorvietnam",

    # ───────── General Vietnam tags ─────────
    "vietnam",
    "vietnamese",
    "vietnamlife",
    "vietnamculture",
    "vietnamtravel",
    "madeinvietnam",
    "hellovietnam",
    "ilovevietnam",
    "visitvietnam",
    "vietnamesestyle"
]

THREADS_MIN_CHARS    = 80    # Lower bar — VI posts are often punchy & short
THREADS_MAX_PER_USER = 80    # Posts per account per run (conservative to avoid bans)

# ── Crawl behaviour tuning ────────────────────────────────────────────────────
# These are read by the crawler for timing and session management.
# Adjust based on observed ban frequency.

THREADS_SCROLL_DELAY_MIN  = 2.0   # seconds between scrolls (min)
THREADS_SCROLL_DELAY_MAX  = 4.5   # seconds between scrolls (max)
THREADS_PAGE_DELAY_MIN    = 5.0   # seconds between page navigations (min)
THREADS_PAGE_DELAY_MAX    = 12.0  # seconds between page navigations (max)
THREADS_SESSION_MAX_PAGES = 12    # pages before rotating browser context
THREADS_MAX_SCROLLS_USER  = 18    # max scrolls per user profile
THREADS_MAX_SCROLLS_TAG   = 14    # max scrolls per hashtag page